import type { Metadata } from "next";
import "./globals.css";
import { Genos } from "next/font/google";

const genos = Genos({
  subsets: ["latin"],
  variable: "--font-genos",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={genos.variable}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
